### ISSUE TITLE
How do you add plugins?

### ISSUE THREAD

**Issue by BrendanMartin** [agoose77/jupyterlab-markup#41]
I have installed the following plugin with npm: 
https://www.npmjs.com/package/markdown-it-image-figures

But I can't figure out how to activate it in the extension.

**Comment by agoose77** [comment]
The plugins system in `jupyterlab-markup` enables the developer to make Jupyter Lab aware of a markdown-it plugin, but you still need to publish a Jupyter Lab extension in order to do this.

The `jupyterlab-markup` extension provides an interface that other extensions can hook into. It's like a central point of integration. All of these other extensions are basically just adaptors into the Jupyter Lab ecosystem. 

If you want to create such an extension, take a look at `jupyterlab-myst` on github for an example of how to do this. You can use the Jupyter Lab cookie-cutter to create the skeleton for the extension.

**Comment by BrendanMartin** [comment]
Do you know of any extensions already out there that hook into jupyterlab-markup and allow installation of any markdown-it plugin?

**Comment by agoose77** [comment]
Yep, take a look at the `src/builtins` directory in this repo - the `simpleMarkdownItPlugin` is the boilerplate that hooks into Jupyter Lab.

You can also look at https://github.com/executablebooks/jupyterlab-myst which connects the MyST plugins to Jupyter Lab

**Comment by BrendanMartin** [comment]
Okay, for now, I just forked the repo and added the image-figures plugin into builtins.

**Comment by agoose77** [comment]
Cool, that's one approach! If you do want to implement a plugin as a JupyterLab extension, feel free to re-open this issue :)
