### ISSUE TITLE
Broken yaml code block syntax highlighting

### ISSUE THREAD

**Issue by s-weigand** [agoose77/jupyterlab-markup#48]
First of all thanks for the awesome extension 😄 

When trying it out I found that the syntax highlighting for `yaml` is broken.
For example this code snipped
<pre>
```yaml
foo:
    bar: [1,2]
```
</pre>

Without the extension, it renders like this
![image](https://user-images.githubusercontent.com/9513634/156550428-c8a5a717-4848-4cdf-86fa-a7cd2dfc3557.png)
And after installing the extension
![image](https://user-images.githubusercontent.com/9513634/156550469-0d2d9115-a032-491e-9ca4-ef4ad12cd6d7.png)

Html markup without extension
![image](https://user-images.githubusercontent.com/9513634/156552075-08365cda-8430-4f9b-9df2-37e12c63568a.png)
Html markup with extension
![image](https://user-images.githubusercontent.com/9513634/156552124-97fd61d6-7338-409f-a1a7-4ad62dedde82.png)

Maybe there is a way to tell `markdown-it` to ignore `yaml` and `yml`?

Other code blocks like `python` and `js` work normally.

**Comment by agoose77** [comment]
I can reproduce this, but I'm not initially sure what the cause is. `jupyterlab-markup` is receiving the highlight request, and passing it off to CM5, but I think something is going wrong thereafter.

**Comment by bollwyvl** [comment]
This is actually the case for _any_ mode which hasn't been loaded yet (a few are _blessed_, e.g. JSON, markdown, python). If it's loaded before the render occurs, it should work: for example, creating a `.yml` file and opening it with the editor, then re-opening a markdown file which has a `yaml` code block looks correct.

A quick look [upstream suggests](https://github.com/jupyterlab/jupyterlab/blob/d7f1704307c2e345f247e1a411bdbae50f2a5708/packages/markedparser-extension/src/index.ts#L69), after determining which mode is needed, we need to call `await Mode.ensure(spec)`... somewhere around [here](https://github.com/agoose77/jupyterlab-markup/blob/fbc31ea8cc6d5bbb314c0d0b670fe61811d88c96/src/manager.ts#L285)... which of course we _can't_ have, directly, because asynchrony.
