### ISSUE TITLE
Accessing notebook cell metadata via a BUILTIN plugin

### ISSUE THREAD

**Issue by psychemedia** [agoose77/jupyterlab-markup#52]
Hi

I note that the [plugin mechanism](https://github.com/agoose77/jupyterlab-markup/issues/41) makes it relatively easy to add your own custom handlers for different sorts of structured content.

Do the plugins also have access to the notebook cell metadata? For example, could a plugin access the `cell.model.metadata`? If so, is there an example of this anywhere?

**Comment by agoose77** [comment]
At present we use the existing JupyterLab scaffolding for Markdown rendering. This means that the Markdown renderer only sees the Markdown source, rather than the cell model. Because of this, it is not currently possible to access the cell through a plugin unless you do this yourself. 

You *could* hack this in - the plugin mechanism is just a wrapper around the JupyterLab extension mechanism. You could write a more advanced extension that references the notebook tracker, and try to do some kind of lookup, but it would be fairly fragile.

**Comment by agoose77** [comment]
In the long run, there is definitely scope for thinking about how cells should interact with Markdown rendering. There are already areas where this has interesting ramifications (https://github.com/agoose77/jupyterlab-imarkdown/)

**Comment by psychemedia** [comment]
> ... the Markdown renderer only sees the Markdown source, rather than the cell model.

Ah, ok... I think that's probably beyond my skillset atm. I did have a look at [jupyterlab-imarkdown/](https://github.com/agoose77/jupyterlab-imarkdown/) and will see if I can get get enough of a grip on it to strip it back to just giving me access to a cell / cell markdown, customising metadata on the basis of tag settings, and then seeing if I can just render that customised markdown.

**Comment by agoose77** [comment]
Dragons beware! It's pretty gnarly code, mainly because JupyterLab's notebook rendering is not very customisable at the moment. `jupyterlab-imarkdown` overrides the machinery that returns a Markdown cell. It returns a special cell that [listens for rendered markdown](https://github.com/agoose77/jupyterlab-imarkdown/blob/49248662a4492a2fc81a8c13c9f370e6bca18c04/src/cell.ts#L183-L203), and post-processes it to identify the special expression syntax. Meanwhile, there is a [separate code](https://github.com/agoose77/jupyterlab-imarkdown/blob/49248662a4492a2fc81a8c13c9f370e6bca18c04/src/index.ts#L96-L104) path that evaluates the parsed cell expressions and replaces the placeholders in the HTML with the rendered results

**Comment by psychemedia** [comment]
Presumably the `model.value.text` is the original, raw markdown. When the markdown cell has rendered, can you also access the rendered output on the cell?

**Comment by agoose77** [comment]
Unfortunately the cell content is not identical to the text given to the markdown renderer - we strip out the math expressions first.

> When the markdown cell has rendered, can you also access the rendered output on the cell?

By default, no. That's what the `imarkdown` extension has to overload the cell class for.

**Comment by psychemedia** [comment]
The design of the notebook handler / renderer all seems completely messed up to me...
